### ISSUE TITLE
[BUG] [ws-sbom-generator] AttributeError: 'Package' object has no attribute 'check_sum'

### ISSUE THREAD

**Issue by tabac-ws** [whitesource-ps/ws-sbom-generator#93]
Hi team,
Please help with the below:

**Bug Description**  
When trying to use the ws-sbom-generator a trackback error of AttributeError appears.

**Steps to Reproduce**  
1. Trying to generate all SPDX formats reports, however, there is an AttributeError:
`INFO 2022-04-25 08:48:55,795 140084034500416 sbom_generator: Writing file: ./WhiteSource Grafana SBOM report-SPDX-2.2.tv in format: tv
Traceback (most recent call last):
  File "/usr/local/bin/ws_sbom_generator", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/ws_sbom_generator/sbom_generator.py", line 397, in main
    file_paths = create_sbom_doc(scope['token'])
  File "/usr/local/lib/python3.8/dist-packages/ws_sbom_generator/sbom_generator.py", line 69, in create_sbom_doc
    file_path = write_report(doc, args.type)
  File "/usr/local/lib/python3.8/dist-packages/ws_sbom_generator/sbom_generator.py", line 316, in write_report
    full_path = write_file(SPDXFileType, doc, f_type)
  File "/usr/local/lib/python3.8/dist-packages/ws_sbom_generator/sbom_generator.py", line 335, in write_file
    module.write_document(doc, fp)
  File "/usr/local/lib/python3.8/dist-packages/spdx/writers/tagvalue.py", line 315, in write_document
    messages = document.validate(messages)
  File "/usr/local/lib/python3.8/dist-packages/spdx/document.py", line 401, in validate
    self.validate_packages(messages)
  File "/usr/local/lib/python3.8/dist-packages/spdx/document.py", line 471, in validate_packages
    messages = package.validate(messages)
  File "/usr/local/lib/python3.8/dist-packages/spdx/package.py", line 125, in validate
    self.validate_checksum(messages)
  File "/usr/local/lib/python3.8/dist-packages/spdx/package.py", line 274, in validate_checksum
    if self.check_sum is not None:
AttributeError: 'Package' object has no attribute 'check_sum'`

**Expected Behavior**  
All reports should be generated.

**Environment Details**  
 - OS: Ubuntu 20.04 container
 - Version: ws-sbom-generator  0.5.7 & ws-spdx-tools      0.7.0a3.post6

Thanks,
Ori.

**Comment by DimarrWS** [comment]
Hi @Ori! Can you provide me , please, data for which you ran sbom_generator ? This is little bit strange issue, I want to reproduce it

**Comment by DimarrWS** [comment]
Hi @tabac-ws ! Can you provide me , please, data for which you ran sbom_generator ? This is little bit strange issue, I want to reproduce it

**Comment by DimarrWS** [comment]
Hi @tabac-ws ! Please, take new version of sbom-generator and retest it. I hope it was fixed.

**Comment by tabac-ws** [comment]
Fixed with ws-sbom-generator=0.6.3

Thank you!
